# Generated by Django 3.0.6 on 2020-06-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=80)),
                ('description', models.TextField(default='')),
                ('code', models.CharField(default='', max_length=8)),
                ('stack', models.CharField(default='', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.Mentor')),
            ],
        ),
    ]
