# Generated by Django 3.0.3 on 2020-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mentees',
            field=models.ManyToManyField(to='mentees.Mentee'),
        ),
    ]
