# Generated by Django 3.0.3 on 2020-04-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_mentees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mentees',
        ),
    ]
