# Generated by Django 3.0.6 on 2020-06-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mentors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('linkedin', models.CharField(default='', max_length=100, null=True)),
                ('github', models.CharField(default='', max_length=100, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to=mentors.models.user_directory_path)),
                ('is_mentor', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
