# Generated by Django 3.0.3 on 2020-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20200411_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_mentor',
            field=models.BooleanField(default=True),
        ),
    ]
