# Generated by Django 3.0.3 on 2020-05-23 19:02

from django.db import migrations, models
import mentors.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentor_is_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='phone',
        ),
        migrations.AddField(
            model_name='mentor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=mentors.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='mentor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
