# Generated by Django 3.0.3 on 2020-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_auto_20200524_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='github',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
