# Generated by Django 3.0.6 on 2020-06-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20200603_0229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=64)),
                ('organization', models.CharField(default=0, max_length=64)),
                ('phone', models.IntegerField(default=0)),
                ('is_mentor', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(related_name='mentee_applications', to='projects.Project')),
                ('selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_mentee', to='projects.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_link', models.CharField(default='', max_length=200)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentees.Mentee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
