# Generated by Django 3.0.3 on 2020-04-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_mentees'),
        ('mentees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='projects',
            field=models.ManyToManyField(related_name='applied_projects', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='mentee',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_project', to='projects.Project'),
        ),
    ]
