# Generated by Django 3.0.3 on 2020-05-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_mentees'),
        ('mentees', '0002_auto_20200415_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='projects',
            field=models.ManyToManyField(related_name='mentee_applications', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_mentee', to='projects.Project'),
        ),
    ]
